export const SCHEDULE_MEETING = 'SCHEDULE_MEETING';
export const RESCHEDULE_MEETING = 'RESCHEDULE_MEETING';
export const DELETE_SCHEDULE_MEETING = 'REMOVE_SCHEDULE_MEETING';
export const CREATE_MEETING = 'CREATE_MEETING';