export const SCHEDULE_MEETING = 'SCHEDULE_MEETING';
export const RESCHEDULE_MEETING = 'RESCHEDULE_MEETING';
export const DELETE_SCHEDULE_MEETING = 'REMOVE_SCHEDULE_MEETING';
export const CREATE_MEETING = 'CREATE_MEETING';
export const CLOSE_ADD_LOCATION_MODAL = 'CLOSE_ADD_LOCATION_MODAL';
export const OPEN_ADD_LOCATION_MODAL = 'OPEN_ADD_LOCATION_MODAL';
export const UPDATE_MEETING_LOCATION = 'UPDATE_MEETING_LOCATION';